### PR TITLE
adds image preview before submitting

### PR DESCRIPTION
**Pull request by iorme1**
issue #67 
Tested this out and it works well to show a thumbnail preview of the photo before you submit. However, you probably will want a default image to display something like "Image Preview" or something.

### CODE REVIEW

**Comment by iorme1** [comment]
I just realized I have a console.log in the javascript that I forgot to remove.  Let me know if you guys are happy with this implementation and I will go ahead and remove that.

**Comment by loudmouse** [comment]
@iorme1 all looks good except the image preview is not right side up - see screenshot. Is it showing the proper orientation for you? If you can fix that we'll go ahead and merge this and I've got a preview image we can add.

screenshot

**Comment by iorme1** [comment]
I just tried doing this preview with a bunch of different images I had on my computer and all of them have the same orientation as the original.

**Comment by loudmouse** [comment]
@iorme1 it looks like it may have just been the images on my computer causing the issue. It seems to be working fine now. Thx!

**Pull request merged**
