### PR TITLE
Adds sample addresses and photos to seed file

### PR DESCRIPTION
**Pull request by iorme1**
Adds sample addresses and photos to seeds.rb file.  Two sample users are created that both have 6 of their own added tank locations/photos.  If anything should be changed in this seed file, just let me know and I will change it immediately. I tested it out locally and it works.

### CODE REVIEW

**Comment by loudmouse** [comment]
@iorme1 nice work on this! A couple changes/questions:

- Can you add city and state to each address in the seed file? When I seed with your current addresses some of these don't recognize as Chicago and instead are mapping in Minnesota and Michigan.
- Along with the above point can you seed the lat/long coordinates of these addresses? 
- Where did you find these images and do we have rights to use them? I love the photos but unless they have some sort of creative commons license we'd need to get permission to use them. 

Nice job on this.

**Comment by iorme1** [comment]
I got the photos from https://buildingupchicago.com/.  I'm not sure where to look but I didn't see anything about these images being copywritten.  However, I checked out the site's contact page and sent an email asking if I could have permission to use the photos on their website to use on this website. And absolutely yes, I will work on adding city/state/lat/long  for the addresses today!

**Comment by iorme1** [comment]
Added city/state/lat/long to seeds and contacted website owner to ask
permission to use photos.

-Isaac

**Comment by iorme1** [comment]
I received in email back from the photo's owner and he said "You may use them as long as they are attributed to "Daniel Schell, Building Up Chicago" ".

**Comment by loudmouse** [comment]
Thanks for checking in on that! Sorry, one more request: can you add neighborhood names to the locations you've added? They don't have to be the correct neighborhood names but just so there is data populated in the database for that field. You can find a list of the neighborhood names in 'tank_locations_helper.rb'.

If you can add that I'll review again and can then go ahead and get this merged.

Thanks again for your patience and for helping with this!

**Comment by iorme1** [comment]
No problem, just added neighborhood to the seed data.

**Comment by loudmouse** [comment]
Thanks for making this change. Sorry, we've since added an attribute for user_name to the user table. Can you make sure each of the users has a username? If you can make that change and submit it back to me I'll review and will merge you this week. Thanks for your patience while waiting for feedback. We really appreciate your interest in contributing.

Also, in regards to your question to @jalletto in your other pull request, you're more than welcome to submit a separate, new pull request if it's easier for you to do that. 

Thanks again, @iorme1.

**Comment by loudmouse** [comment]
@iorme1 thanks for your patience on this one! This looks good and really appreciate you contributing to the project. Since I already have a couple handfuls of real water tanks mapped with photos I swapped these out in the seed file you'd created - I hope you don't mind. All else looks good so I'm merging this to master. Thanks again!

**Pull request merged**
