### PR TITLE
User profile/nolan

### PR DESCRIPTION
**Pull request by loudmouse**
@jalletto we can review and discuss on this call tonight.

### CODE REVIEW

**Comment by loudmouse** [comment]
@jalletto alright this is good to go. Feel free to merge if it looks good to you.

**Comment by loudmouse** [comment]
If you go to your profile page and haven't mapped a tank you'll see this:
screenshot 3

If you're logged in and visit your profile page then you'll see your activity:
screenshot 4

**Comment by jalletto** [comment]
sweet. tell amanda to get on it.

**Comment by loudmouse** [comment]
haha. Being pregnant is no excuse for not mapping water tanks!

**Comment by jalletto** [comment]
haha

**Pull request merged**
